# This workflow will install Python dependencies, install package, and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyTests

on:
  push: # Trigger the workflow on any push
    branches:
      - '*' # Run on all branches
  pull_request: # Trigger the workflow on pull requests
    branches:
      - '*' # Run on all branches

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install the package
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pytest
