# This workflow will install Python dependencies, install package, and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyTests

on:
  push: # Trigger the workflow on any push
    branches:
      - '*' # Run on all branches
  pull_request: # Trigger the workflow on pull requests
    branches:
      - '*' # Run on all branches

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  pytest-cov coverage coverage-badge
    - name: Install the package
      run: |
        pip install .
    - name: Test with pytest and calculate coverage
      run: |
        coverage run --source=scengen -m pytest --junitxml=report.xml
        coverage report -m
        coverage html
    - name: Generate coverage badge
      run: |
        coverage-badge -o coverage.svg
    - name: Upload badge to repository
      run: |
        mv coverage.svg docu/
    - name: Update README.md with badge
      run: |
        echo '![](docu/coverage.svg)' >> README.md
